create table admin (id bigint not null auto_increment, admin_age integer, admin_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table option_table (id bigint not null auto_increment, answer varchar(255), primary key (id)) engine=InnoDB;
create table ques_quiz (quiz_id bigint, ques_id bigint not null, primary key (ques_id)) engine=InnoDB;
create table question (id bigint not null auto_increment, ques_description varchar(255) not null, correct_option_id bigint, primary key (id)) engine=InnoDB;
create table question_options (question_id bigint not null, options_id bigint not null, primary key (question_id, options_id)) engine=InnoDB;
create table quiz (id bigint not null auto_increment, is_running TINYINT, create_time datetime, quiz_description varchar(255), quiz_title varchar(255) not null, primary key (id)) engine=InnoDB;
create table quiz_topics (quiz_id bigint not null, topic_id bigint not null, primary key (quiz_id, topic_id)) engine=InnoDB;
create table student (id bigint not null auto_increment, student_education varchar(255) not null, student_name varchar(255) not null, primary key (id)) engine=InnoDB;
create table student_quiz (score integer, quiz_id bigint not null, student_id bigint not null, primary key (quiz_id, student_id)) engine=InnoDB;
create table topic (id bigint not null auto_increment, topic_code varchar(255) not null, topic_description varchar(255), topic_name varchar(255) not null, primary key (id)) engine=InnoDB;
alter table question_options add constraint UK_pb9aj69m72t1y7x3ovlprhw5g unique (options_id);
alter table topic add constraint UK_ks0fs0t6bmx6eaggrg4x6qs76 unique (topic_code);
alter table ques_quiz add constraint FKkualr1nj5be4rgo0omg4p9ehp foreign key (quiz_id) references quiz (id);
alter table ques_quiz add constraint FK48qnap9ok4obsmrlr871qvi28 foreign key (ques_id) references question (id);
alter table question add constraint FKfsc6iiw1qhrj37kuf73mb40yc foreign key (correct_option_id) references option_table (id);
alter table question_options add constraint FKp9qx9tgm6d0s9c0iqaajt2q35 foreign key (options_id) references option_table (id);
alter table question_options add constraint FKjk4v42xhyfv4ca1yyhorsg5tv foreign key (question_id) references question (id);
alter table quiz_topics add constraint FK7g8peb2cpqal280n9nfenjwfh foreign key (topic_id) references topic (id);
alter table quiz_topics add constraint FKpa5pqsjv6pks2vyh3p40xyyml foreign key (quiz_id) references quiz (id);
alter table student_quiz add constraint FK2vlc8g4tri8x3cc754uyxrkbh foreign key (quiz_id) references quiz (id);
alter table student_quiz add constraint FKkqatm8ii2xdx8iqd9ruoolrbk foreign key (student_id) references student (id);
